### ISSUE TITLE
suggestion of usage

### ISSUE THREAD

**Issue by ctf0** [voxtobox/vue-scroll-stop#1]
i believe the package mimics the main behavior of `overscroll-behavior`

https://caniuse.com/#search=overscroll-behavior
https://developers.google.com/web/updates/2017/11/overscroll-behavior

so if u want maybe we can add those info to the readme or even extract the code to a separate lib so everyone can use it whether is using vue or not :+1:

**Comment by voxtobox** [comment]
@ctf0 Great idea! Perhaps we can detect whether browser supports `overscroll-behavior` and use directive only as a polyfill?

**Comment by ctf0** [comment]
maybe if u separated the logic into its own lib as a polyfill then yes but in its current state "a lib for vue" i don't think we need the detection.

**Comment by Grawl** [comment]
if someone find a polyfill for `overscroll-behaviour` please add link here

**Comment by Grawl** [comment]
for now, I wrote this:

```js
import VueScrollStop from 'vue-scroll-stop'
if (CSS.supports('overscroll-behavior', 'contain')) {
	console.log('[v-scroll-stop] is disabled, use `overscroll-behavior: contain` instead')
} else {
	console.log('`overscroll-behavior: contain` is not supported, use [v-scroll-stop]')
	Vue.use(VueScrollStop)
}
```
